# Using the official MongoDB image directly from docker-compose file is simpler and more straightforward
# while building a custom Docker image using a Dockerfile for a mongo container (like this example) will give you greater flexibility and customization options. 
# The choice between the two depends on your specific use case and requirements.
FROM mongo

# ... More configuration comes here ...